import { Permission, Role, RoleData } from "./types";

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  admin: [
    "admin.*",
    "dashboard.view",
    "dashboard.manage",
    "users.view",
    "users.create",
    "users.edit",
    "users.delete",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "tasks.delete",
    "tasks.assign",
    "leaves.view",
    "leaves.create",
    "leaves.approve",
    "leaves.reject",
    "leaves.cancel",
    "reports.view",
    "reports.export",
    "settings.view",
    "settings.manage",
  ],
  manager: [
    "manager.*",
    "dashboard.view",
    "users.view",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "tasks.assign",
    "leaves.view",
    "leaves.approve",
    "leaves.reject",
    "reports.view",
    "reports.export",
  ],
  hr: [
    "hr.*",
    "dashboard.view",
    "users.view",
    "users.create",
    "users.edit",
    "leaves.view",
    "leaves.approve",
    "leaves.reject",
    "reports.view",
    "reports.export",
  ],
  supervisor: [
    "dashboard.view",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "tasks.assign",
    "leaves.view",
    "leaves.approve",
    "reports.view",
  ],
  employee: ["dashboard.view", "tasks.view", "leaves.view", "leaves.create"],
  provider: ["dashboard.view", "tasks.view"],
  guest: ["dashboard.view"],
};

export const ROLE_HIERARCHY: Record<Role, number> = {
  admin: 100,
  manager: 80,
  hr: 70,
  supervisor: 60,
  employee: 40,
  provider: 30,
  guest: 10,
};

export const ROLE_DATA: Record<Role, RoleData> = {
  admin: {
    name: "admin",
    displayName: "Administrator",
    description: "Full system access and control",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.admin,
  },
  manager: {
    name: "manager",
    displayName: "Manager",
    description: "Manages team and approves requests",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.manager,
  },
  hr: {
    name: "hr",
    displayName: "HR Manager",
    description: "Manages human resources and leave requests",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.hr,
  },
  supervisor: {
    name: "supervisor",
    displayName: "Supervisor",
    description: "Supervises team and tasks",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.supervisor,
  },
  employee: {
    name: "employee",
    displayName: "Employee",
    description: "Standard employee access",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.employee,
  },
  provider: {
    name: "provider",
    displayName: "Provider",
    description: "External service provider",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.provider,
  },
  guest: {
    name: "guest",
    displayName: "Guest",
    description: "Limited read-only access",
    isActive: true,
    permissions: DEFAULT_ROLE_PERMISSIONS.guest,
  },
};
